import type { Metadata } from "next";
import { Inter, Noto_Sans_KR } from "next/font/google";
import "./globals.css";

const notoSansKR = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "700", "900"],
  style: ["normal"],
  variable: "--notoSansKR" /* tailwind.config.ts에서 변수 설정 */,
});
const inter = Inter({ subsets: ["latin"] });

/* 로컬 폰트 사용 방법
const metallica = localFont({
  src: "./metallica.ttf",
  variable: "--metallica-text",
});
*/

export const metadata: Metadata = {
  title: "Painter Next Door",
  description: "Generated by Kosmosticlay",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansKR.variable} bg-stone-800 text-white`}>
        {children}
      </body>
    </html>
  );
}
